import { useRef, useState } from 'react';
import { Box, Button, Card, TextField, Typography } from '@mui/material';
import { FileUp, Printer } from 'lucide-react';
import SEO from '../../components/SEO';
import MarkdownPreview from '../../components/tools/MarkdownPreview';

const DEFAULT_MARKDOWN = `# The Definitive Report Nobody Asked For

> Lovingly generated by a large language model, polished here so everyone thinks you wrote it.

## Executive Summary

You pasted AI output into a box. This tool turns it into a PDF. Congratulations on your **workflow**.

## Deliverables That Sound Impressive

| Deliverable | Claimed Effort | Actually Done By |
| --- | --- | --- |
| Strategy deck | 3 weeks | ChatGPT, 40 seconds |
| Q3 roadmap | 2 sprints | Autocomplete |
| This document | "an all-nighter" | You, pressing Ctrl+V |

## The Process

\`\`\`mermaid
flowchart LR
  A[Vague prompt] --> B[AI slop]
  B --> C{Did you read it?}
  C -- No --> D[Paste it here]
  C -- Also no --> D
  D --> E[Respectable PDF]
  E --> F[Promotion, probably]
\`\`\`

## Technical Bits

Inline code like \`rm -rf doubts\` renders too, and so do blocks:

\`\`\`js
function addValue() {
  return 'value'; // synergy achieved
}
\`\`\`

1. Paste markdown
2. Admire the live preview
3. Click Download PDF
4. Tell everyone you "wrote a report"

Further reading at [a link you will never click](https://example.com).
`;

const PRINT_STYLES = `
@page {
  margin: 2cm;
}
@media print {
  html, body {
    background: #ffffff !important;
  }
  body * {
    visibility: hidden !important;
  }
  .md-print-area,
  .md-print-area * {
    visibility: visible !important;
  }
  .md-print-area {
    display: block !important;
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    margin: 0 !important;
    padding: 0 !important;
    background: #ffffff !important;
  }
  .md-print-area * {
    color: #000000 !important;
    background: transparent !important;
    border-color: #999999 !important;
    box-shadow: none !important;
    text-shadow: none !important;
    font-family: Georgia, 'Times New Roman', serif;
  }
  .md-print-area pre,
  .md-print-area code {
    font-family: 'Courier New', Courier, monospace;
    white-space: pre-wrap !important;
    word-break: break-word !important;
    overflow: visible !important;
  }
  .md-print-area table {
    break-inside: auto;
  }
  .md-print-area tr {
    break-inside: avoid;
    page-break-inside: avoid;
  }
  .md-print-area h1,
  .md-print-area h2,
  .md-print-area h3,
  .md-print-area h4,
  .md-print-area h5,
  .md-print-area h6 {
    break-after: avoid;
    page-break-after: avoid;
  }
  .md-print-area a {
    text-decoration: underline;
  }
  .md-print-area svg {
    max-width: 100% !important;
  }
}
`;

export default function MarkdownPolisher() {
  const [markdown, setMarkdown] = useState(DEFAULT_MARKDOWN);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFile = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => setMarkdown(String(reader.result ?? ''));
    reader.readAsText(file);
    event.target.value = '';
  };

  return (
    <Box className="min-h-screen pt-32 pb-20 px-6" sx={{ bgcolor: 'background.default' }}>
      <SEO
        title="The AI Slop Polisher"
        description="Launder your ChatGPT output into a respectable PDF. Markdown in, plausible deniability out. Tables, code, even mermaid diagrams — nobody will suspect a thing."
        keywords={['Markdown to PDF', 'Markdown renderer', 'Mermaid diagrams', 'AI slop', 'ChatGPT output formatter']}
      />
      <style>{PRINT_STYLES}</style>

      <Box sx={{ maxWidth: 1200, mx: 'auto' }}>
        <Box sx={{ textAlign: 'center', mb: 5 }}>
          <Typography variant="h4" component="h1" sx={{ fontWeight: 'bold', color: 'text.primary', mb: 2 }}>
            The AI Slop Polisher
          </Typography>
          <Typography sx={{ color: 'text.secondary' }}>
            Paste whatever the robot wrote, pretend you proofread it, export a respectable PDF.
            It's the AI era; nobody's checking.
          </Typography>
        </Box>

        <Card elevation={8} sx={{ borderRadius: 4, overflow: 'hidden' }}>
          {/* Toolbar */}
          <Box
            sx={{
              display: 'flex',
              flexWrap: 'wrap',
              alignItems: 'center',
              gap: 1,
              p: 1.5,
              borderBottom: '1px solid',
              borderColor: 'divider',
              bgcolor: 'background.default',
            }}
          >
            <input
              ref={fileInputRef}
              type="file"
              accept=".md,.markdown,.txt"
              onChange={handleFile}
              style={{ display: 'none' }}
            />
            <Button
              variant="outlined"
              startIcon={<FileUp className="w-4 h-4" />}
              onClick={() => fileInputRef.current?.click()}
            >
              Upload .md
            </Button>
            <Typography sx={{ color: 'text.secondary', fontSize: '0.75rem', display: { xs: 'none', sm: 'block' } }}>
              .md, .markdown or .txt — we don't judge the extension, only the content.
            </Typography>
            <Button
              variant="contained"
              startIcon={<Printer className="w-4 h-4" />}
              onClick={() => window.print()}
              sx={{ fontWeight: 'bold', ml: { sm: 'auto' }, width: { xs: '100%', sm: 'auto' } }}
            >
              Download PDF
            </Button>
          </Box>

          {/* Editor + Preview */}
          <Box
            sx={{
              display: 'grid',
              gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' },
              height: { md: 620 },
            }}
          >
            <TextField
              multiline
              value={markdown}
              onChange={(e) => setMarkdown(e.target.value)}
              placeholder="Paste your finest machine-generated prose here..."
              sx={{
                width: '100%',
                height: { xs: 320, md: '100%' },
                borderRight: { md: '1px solid' },
                borderBottom: { xs: '1px solid', md: 'none' },
                borderColor: { xs: 'divider', md: 'divider' },
                '& .MuiInputBase-root': {
                  height: '100%',
                  alignItems: 'flex-start',
                  p: 0,
                  borderRadius: 0,
                  bgcolor: 'transparent',
                },
                '& .MuiInputBase-input': {
                  height: '100% !important',
                  overflow: 'auto !important',
                  color: 'text.primary',
                  fontFamily: '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
                  fontSize: '0.85rem',
                  lineHeight: 1.625,
                  p: 2,
                },
                '& .MuiOutlinedInput-notchedOutline': { border: 'none' },
              }}
            />
            <Box sx={{ height: { md: '100%' }, overflowY: { md: 'auto' }, p: 3, bgcolor: 'background.paper' }}>
              {markdown.trim() ? (
                <MarkdownPreview markdown={markdown} />
              ) : (
                <Typography sx={{ color: 'text.secondary', fontStyle: 'italic' }}>
                  The preview is empty. So is the report, apparently.
                </Typography>
              )}
            </Box>
          </Box>
        </Card>

        <Typography sx={{ textAlign: 'center', color: 'text.secondary', fontSize: '0.75rem', mt: 3 }}>
          "Download PDF" opens your browser's print dialog. Choose "Save as PDF". Yes, that counts as downloading.
        </Typography>
      </Box>

      {/* Dedicated print view: hidden on screen, the only thing visible on paper */}
      <Box className="md-print-area" sx={{ display: 'none' }}>
        <MarkdownPreview markdown={markdown} forceLightMermaid />
      </Box>
    </Box>
  );
}
